# 日志配置
logging:
  level:
    cn.sduwh.wechatserver: info
  path: ./logs

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: 201600800543
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    # Druid配置
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 100
    maxActive: 1000
    minIdle: 100
    maxWait: 60000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    minEvictableIdleTimeMillis: 300000
    filters: stat, wall, slf4j

  # thymeleaf
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-idle: 500
        max-active: 500
    timeout: 10ms




# ORM
mybatis:
  # 实体类包扫描
  type-aliases-package: cn.personal.seckill.entity
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
